apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: fastapi
spec:
  gateways:
  - default/bookinfo-gateway
  hosts:
  - '*'
  http:
  - name: "main"
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: fastapi
        port:
          number: 8080